// <auto-generated />
using System;
using AppProject.Repository.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppProject.Repository.Migrations
{
    [DbContext(typeof(AppProjectDbContext))]
    partial class AppProjectDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AppProject.Model.Entities.User.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by")
                        .HasComment("创建人");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_time")
                        .HasComment("创建时间");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_modified")
                        .HasComment("修改时间");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("last_modified_by")
                        .HasComment("修改人");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password")
                        .HasComment("用户密码");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("user_name")
                        .HasComment("用户名");

                    b.Property<string>("UserNickName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("user_nickname")
                        .HasComment("用户别名");

                    b.HasKey("Id");

                    b.ToTable("user");
                });

            modelBuilder.Entity("AppProject.Model.TestModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("desc");

                    b.HasKey("id");

                    b.ToTable("test_model");
                });
#pragma warning restore 612, 618
        }
    }
}
